### PR TITLE
merge to develop

### PR DESCRIPTION
**Pull request by Abdusaid10**

### CODE REVIEW

**Comment by AdnanAfsari** [comment]
### **Adnan Afsari working on it**

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @Abdusaid10 @emmanuelkamala ✋ 

Looks good so far but you have to work little more, I tried to run the test on my local machine, all of the test passed but getting this error so there is a room to improve.
Screenshot 2019-07-29 at 11 46 48 PM

- Try to fix this error

- Your project should have a descriptive README.Update your README.

Please submit for another review after making those changes.

happy coding :)

**Comment by JamesOkunlade** [comment]
James working on it

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hello @Abdusaid10  and @emmanuelkamala 

Tests look really good and passing well. However, you have not updated your README.md file as requested by the previous reviewer.

Please do this and request a review for it.

**Comment by JamesOkunlade** [comment]
James is working on it.

**Review by JamesOkunlade — APPROVED** [review]
Congrats :tada: on completing the project. :+1:

Go ahead and merge. Good luck with your future projects.

**Pull request merged**
